# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'console.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Console(object):
    def setupUi(self, Console):
        Console.setObjectName("Console")
        Console.resize(400, 350)
        Console.setMinimumSize(QtCore.QSize(400, 350))
        self.log = QtWidgets.QTextEdit(Console)
        self.log.setGeometry(QtCore.QRect(0, 10, 401, 291))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.log.setFont(font)
        self.log.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.log.setReadOnly(True)
        self.log.setPlaceholderText("")
        self.log.setObjectName("log")
        self.closeconsole = QtWidgets.QPushButton(Console)
        self.closeconsole.setGeometry(QtCore.QRect(150, 300, 88, 34))
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::ListRemove")
        self.closeconsole.setIcon(icon)
        self.closeconsole.setObjectName("closeconsole")

        self.retranslateUi(Console)
        QtCore.QMetaObject.connectSlotsByName(Console)

    def retranslateUi(self, Console):
        _translate = QtCore.QCoreApplication.translate
        Console.setWindowTitle(_translate("Console", "Form"))
        self.closeconsole.setText(_translate("Console", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Console = QtWidgets.QWidget()
    ui = Ui_Console()
    ui.setupUi(Console)
    Console.show()
    sys.exit(app.exec_())
